### PR TITLE
Make uvicorn logs be JSON. Refactor json_logging config

### PR DESCRIPTION
**Pull request by pawbu**
As noted [here](https://github.com/br3ndonland/inboard/pull/3) logging is quite complicated with uvicorn. 
I followed the advice [here](https://github.com/tiangolo/fastapi/issues/1508#issuecomment-851125448) and that worked nicely.

### CODE REVIEW

**Review by vaskalan — APPROVED** [review]
Nice! :-)

**Comment by FISHMANPET** [comment]
I stumbled on this, since you referenced this issue [here](https://github.com/tiangolo/fastapi/issues/1508) and decided to shamelessly copy it.  One problem I noticed, in your log_config.yaml, the closing quote in your format strings is off, it should be this: ` "message": "%(message)s"}`.  Inside the bracket, to close off the message value, rather than outside the bracket.

However, that still doesn't generate "valid" JSON, specifically in the access logs.  An access event message will look like this:
`127.0.0.1:59506 - "GET /openapi.json HTTP/1.1" 200 OK` including the quotes, so when that gets logged unescaped it becomes invalid JSON.  I don't have an answer for that problem yet, but at least thought you should be aware.

**Comment by pawbu** [comment]
@FISHMANPET Good catch, thanks. We'll take a look at this issue.

**Comment by pawbu** [comment]
@FISHMANPET The fastapi-request-logger from FastAPI is enough for us right now so I removed log_config.yaml from the project.
https://github.com/encode/uvicorn/issues/680#issuecomment-631519178 looks promising though.

**Pull request merged**
